import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PageTransition } from "@/components/PageTransition";
import Nav from "@/components/Nav";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={`${inter.className} text-[#eeebd8] antialiased`}>
                <PageTransition>
                    <Nav />
                    <main className="page-content">{children}</main>
                </PageTransition>
            </body>
        </html>
    );
}
